### ISSUE TITLE
Suggestion: dotbot for install.sh

### ISSUE THREAD

**Issue by issmirnov** [thenyeguy/dotfiles#1]
I noticed you have a homerolled install.sh for the symlinks. This works great while the number of files is small, but doesn't scale well if you decide to add more files. I found [dotbot](https://github.com/anishathalye/dotbot/tree/master) immensely useful for this. [my config](https://github.com/issmirnov/dotfiles/blob/master/default.conf.yaml) has the basics, and the [installer](https://github.com/issmirnov/dotfiles/blob/master/install) will branch on `$OS` and fork to Darwin or Debian as needed.

HTH.

**Comment by thenyeguy** [comment]
That's neat! I try not to depend on external dependencies when possible, but I like the features, and ended up rewriting my install script in python with many of the dotbot features I like.
